// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sprinklers.proto

package sprinklers

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Circuit struct {
	Name                 string             `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	WaterConsumption     float64            `protobuf:"fixed64,2,opt,name=WaterConsumption,proto3" json:"WaterConsumption,omitempty"`
	State                bool               `protobuf:"varint,3,opt,name=State,proto3" json:"State,omitempty"`
	TimeRemaining        *duration.Duration `protobuf:"bytes,4,opt,name=TimeRemaining,proto3" json:"TimeRemaining,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Circuit) Reset()         { *m = Circuit{} }
func (m *Circuit) String() string { return proto.CompactTextString(m) }
func (*Circuit) ProtoMessage()    {}
func (*Circuit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c75169631e9774f8, []int{0}
}

func (m *Circuit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Circuit.Unmarshal(m, b)
}
func (m *Circuit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Circuit.Marshal(b, m, deterministic)
}
func (m *Circuit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Circuit.Merge(m, src)
}
func (m *Circuit) XXX_Size() int {
	return xxx_messageInfo_Circuit.Size(m)
}
func (m *Circuit) XXX_DiscardUnknown() {
	xxx_messageInfo_Circuit.DiscardUnknown(m)
}

var xxx_messageInfo_Circuit proto.InternalMessageInfo

func (m *Circuit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Circuit) GetWaterConsumption() float64 {
	if m != nil {
		return m.WaterConsumption
	}
	return 0
}

func (m *Circuit) GetState() bool {
	if m != nil {
		return m.State
	}
	return false
}

func (m *Circuit) GetTimeRemaining() *duration.Duration {
	if m != nil {
		return m.TimeRemaining
	}
	return nil
}

type ListCircuitsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCircuitsRequest) Reset()         { *m = ListCircuitsRequest{} }
func (m *ListCircuitsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCircuitsRequest) ProtoMessage()    {}
func (*ListCircuitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c75169631e9774f8, []int{1}
}

func (m *ListCircuitsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCircuitsRequest.Unmarshal(m, b)
}
func (m *ListCircuitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCircuitsRequest.Marshal(b, m, deterministic)
}
func (m *ListCircuitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCircuitsRequest.Merge(m, src)
}
func (m *ListCircuitsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCircuitsRequest.Size(m)
}
func (m *ListCircuitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCircuitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCircuitsRequest proto.InternalMessageInfo

type ListCircuitsResponse struct {
	Items                []*Circuit `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListCircuitsResponse) Reset()         { *m = ListCircuitsResponse{} }
func (m *ListCircuitsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCircuitsResponse) ProtoMessage()    {}
func (*ListCircuitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c75169631e9774f8, []int{2}
}

func (m *ListCircuitsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCircuitsResponse.Unmarshal(m, b)
}
func (m *ListCircuitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCircuitsResponse.Marshal(b, m, deterministic)
}
func (m *ListCircuitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCircuitsResponse.Merge(m, src)
}
func (m *ListCircuitsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCircuitsResponse.Size(m)
}
func (m *ListCircuitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCircuitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCircuitsResponse proto.InternalMessageInfo

func (m *ListCircuitsResponse) GetItems() []*Circuit {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Circuit)(nil), "sprinklers.Circuit")
	proto.RegisterType((*ListCircuitsRequest)(nil), "sprinklers.ListCircuitsRequest")
	proto.RegisterType((*ListCircuitsResponse)(nil), "sprinklers.ListCircuitsResponse")
}

func init() { proto.RegisterFile("sprinklers.proto", fileDescriptor_c75169631e9774f8) }

var fileDescriptor_c75169631e9774f8 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0x86, 0x8d, 0xdb, 0xfc, 0x38, 0x53, 0x28, 0xd9, 0x84, 0xba, 0x0b, 0x0d, 0xbd, 0xaa, 0x5e,
	0x74, 0x50, 0x7f, 0x80, 0xc8, 0xbc, 0x11, 0xc4, 0x8b, 0x54, 0xf0, 0x3a, 0x9b, 0xc7, 0x12, 0x5c,
	0x92, 0x9a, 0x0f, 0x7f, 0x8f, 0x3f, 0x55, 0x6c, 0x3a, 0xec, 0xd0, 0xdd, 0x25, 0xef, 0x79, 0xde,
	0xf0, 0xe4, 0x40, 0xe2, 0x1a, 0x2b, 0xf5, 0xfb, 0x1a, 0xad, 0x2b, 0x1a, 0x6b, 0xbc, 0xa1, 0xf0,
	0x9b, 0xcc, 0x2e, 0x6a, 0x63, 0xea, 0x35, 0xce, 0xdb, 0xc9, 0x32, 0xbc, 0xcd, 0x5f, 0x83, 0x15,
	0x5e, 0x1a, 0x1d, 0xd9, 0xec, 0x8b, 0xc0, 0xe1, 0x42, 0xda, 0x55, 0x90, 0x9e, 0x52, 0x18, 0x3e,
	0x09, 0x85, 0x29, 0x61, 0x24, 0x3f, 0xe6, 0xed, 0x99, 0x5e, 0x43, 0xf2, 0x22, 0x3c, 0xda, 0x85,
	0xd1, 0x2e, 0xa8, 0xe6, 0xa7, 0x99, 0xee, 0x33, 0x92, 0x13, 0xfe, 0x27, 0xa7, 0x53, 0x18, 0x55,
	0x5e, 0x78, 0x4c, 0x07, 0x8c, 0xe4, 0x47, 0x3c, 0x5e, 0xe8, 0x2d, 0x9c, 0x3e, 0x4b, 0x85, 0x1c,
	0x95, 0x90, 0x5a, 0xea, 0x3a, 0x1d, 0x32, 0x92, 0x8f, 0xcb, 0xf3, 0x22, 0x9a, 0x15, 0x1b, 0xb3,
	0xe2, 0xbe, 0x33, 0xe3, 0xdb, 0x7c, 0x76, 0x06, 0x93, 0x47, 0xe9, 0x7c, 0x67, 0xe9, 0x38, 0x7e,
	0x04, 0x74, 0x3e, 0xbb, 0x83, 0xe9, 0x76, 0xec, 0x1a, 0xa3, 0x1d, 0xd2, 0x2b, 0x18, 0x3d, 0x78,
	0x54, 0x2e, 0x25, 0x6c, 0x90, 0x8f, 0xcb, 0x49, 0xd1, 0xdb, 0x4f, 0x07, 0xf3, 0x48, 0x94, 0x35,
	0x24, 0xd5, 0x66, 0x58, 0xa1, 0xfd, 0x94, 0x2b, 0xa4, 0x15, 0x9c, 0xf4, 0x9f, 0xa5, 0x97, 0xfd,
	0xfe, 0x3f, 0x1e, 0x33, 0xb6, 0x1b, 0x88, 0x46, 0xd9, 0xde, 0xf2, 0xa0, 0xfd, 0xe4, 0xcd, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x5f, 0xb8, 0xee, 0xac, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SprinklerServiceClient is the client API for SprinklerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SprinklerServiceClient interface {
	ListCircuits(ctx context.Context, in *ListCircuitsRequest, opts ...grpc.CallOption) (*ListCircuitsResponse, error)
}

type sprinklerServiceClient struct {
	cc *grpc.ClientConn
}

func NewSprinklerServiceClient(cc *grpc.ClientConn) SprinklerServiceClient {
	return &sprinklerServiceClient{cc}
}

func (c *sprinklerServiceClient) ListCircuits(ctx context.Context, in *ListCircuitsRequest, opts ...grpc.CallOption) (*ListCircuitsResponse, error) {
	out := new(ListCircuitsResponse)
	err := c.cc.Invoke(ctx, "/sprinklers.SprinklerService/ListCircuits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SprinklerServiceServer is the server API for SprinklerService service.
type SprinklerServiceServer interface {
	ListCircuits(context.Context, *ListCircuitsRequest) (*ListCircuitsResponse, error)
}

// UnimplementedSprinklerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSprinklerServiceServer struct {
}

func (*UnimplementedSprinklerServiceServer) ListCircuits(ctx context.Context, req *ListCircuitsRequest) (*ListCircuitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCircuits not implemented")
}

func RegisterSprinklerServiceServer(s *grpc.Server, srv SprinklerServiceServer) {
	s.RegisterService(&_SprinklerService_serviceDesc, srv)
}

func _SprinklerService_ListCircuits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCircuitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprinklerServiceServer).ListCircuits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sprinklers.SprinklerService/ListCircuits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprinklerServiceServer).ListCircuits(ctx, req.(*ListCircuitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SprinklerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sprinklers.SprinklerService",
	HandlerType: (*SprinklerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCircuits",
			Handler:    _SprinklerService_ListCircuits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sprinklers.proto",
}
